### ISSUE TITLE
Plain broken

### ISSUE THREAD

**Issue by mjflan** [Azure-Samples/active-directory-node-webapi#29]
Fails immediately with 
$ node app.js
util.js:938
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:938:11)
    at Object.<anonymous> (/home/mjflan/work/AzureAD-proto/active-directory-node-webapi/node-server/node_modules/spdy/lib/spdy/connection.js:86:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mjflan/work/AzureAD-proto/active-directory-node-webapi/node-server/node_modules/spdy/lib/spdy.js:20:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

**Comment by derisen** [comment]
Closing this issue as there's a more recent sample [here](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2)
